import type { ScrapedSchoolData } from "@/lib/calculatorUtils";

export const CALCULATOR_SEED_SCHOOLS: ScrapedSchoolData[] = [
  {
    school_name: "Bangkok Patana School",
    homepage_url: "https://www.patana.ac.th",
    status: "ok",
    page_scraped: "https://www.patana.ac.th/admissions/tuition-and-fees/",
    curriculum: "British",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Nursery", order_start: 1, order_end: 1, display_name: "เตรียมอนุบาล (Nursery)", level_code: "PRE_NURSERY", annual_thb: 515000, notes: "Academic Year 2026/27" },
      { grade_level: "Foundation Stage 1", order_start: 2, order_end: 2, display_name: "อนุบาล 1 (Foundation Stage 1)", level_code: "KINDERGARTEN", annual_thb: 577000, notes: "Academic Year 2026/27" },
      { grade_level: "Foundation Stage 2", order_start: 3, order_end: 3, display_name: "อนุบาล 2 (Foundation Stage 2)", level_code: "KINDERGARTEN", annual_thb: 640000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 1 - Year 2", order_start: 5, order_end: 6, display_name: "ประถมศึกษาปีที่ 1–2 (Year 1–2)", level_code: "PRIMARY", annual_thb: 749000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 3", order_start: 7, order_end: 7, display_name: "ประถมศึกษาปีที่ 3 (Year 3)", level_code: "PRIMARY", annual_thb: 790000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 4 - Year 5", order_start: 8, order_end: 9, display_name: "ประถมศึกษาปีที่ 4–5 (Year 4–5)", level_code: "PRIMARY", annual_thb: 796000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 6", order_start: 10, order_end: 10, display_name: "ประถมศึกษาปีที่ 6 (Year 6)", level_code: "PRIMARY", annual_thb: 811000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 7 - Year 9", order_start: 11, order_end: 13, display_name: "มัธยมศึกษาปีที่ 1–3 (Year 7–9)", level_code: "LOWER_SECONDARY", annual_thb: 842000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 10", order_start: 14, order_end: 14, display_name: "มัธยมศึกษาปีที่ 4 (Year 10)", level_code: "UPPER_SECONDARY", annual_thb: 957000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 11", order_start: 15, order_end: 15, display_name: "มัธยมศึกษาปีที่ 5 (Year 11)", level_code: "UPPER_SECONDARY", annual_thb: 707000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 12", order_start: 16, order_end: 16, display_name: "มัธยมศึกษาปีที่ 6 (Year 12)", level_code: "UPPER_SECONDARY", annual_thb: 1014000, notes: "Academic Year 2026/27" },
      { grade_level: "Year 13", order_start: 16, order_end: 16, display_name: "มัธยมศึกษาปีที่ 6 (Year 13)", level_code: "UPPER_SECONDARY", annual_thb: 749000, notes: "Academic Year 2026/27" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 4000, notes: "once only" },
      { name: "Entrance Fee (First Child)", amount_thb: 250000, notes: "once only, non-refundable" },
      { name: "Entrance Fee (Second Child)", amount_thb: 200000, notes: "once only, non-refundable" },
      { name: "Deposit", amount_thb: 50000, notes: "refundable upon withdrawal" },
      { name: "Capital Assessment Fee", amount_thb: 30000, notes: "billed termly" },
      { name: "Extra-Curricular Activities Administrative Charge", amount_thb: 450, notes: "per student per ECA block" },
    ],
    tuition_min_thb: 515000,
    tuition_max_thb: 1014000,
  },
  {
    school_name: "Ruamrudee International School",
    homepage_url: "https://www.rism.ac.th",
    status: "ok",
    page_scraped: "https://www.rism.ac.th/admissions/tuition-fees/",
    curriculum: "American",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Pre-K & KG (2-4)", order_start: 0, order_end: 4, display_name: "เตรียมอนุบาล – อนุบาล 3 (Pre-K & Kindergarten)", level_code: "KINDERGARTEN", annual_thb: 538400, notes: "Combined annual fees" },
      { grade_level: "Grade 1", order_start: 5, order_end: 5, display_name: "ประถมศึกษาปีที่ 1 (Grade 1)", level_code: "PRIMARY", annual_thb: 544400, notes: "Combined annual fees" },
      { grade_level: "Grades 2-5", order_start: 6, order_end: 9, display_name: "ประถมศึกษาปีที่ 2–5 (Grades 2–5)", level_code: "PRIMARY", annual_thb: 718400, notes: "Combined annual fees" },
      { grade_level: "Grades 6-8", order_start: 10, order_end: 12, display_name: "มัธยมศึกษาปีที่ 1–3 (Grades 6–8)", level_code: "LOWER_SECONDARY", annual_thb: 686000, notes: "Combined annual fees" },
      { grade_level: "Grades 9-11", order_start: 13, order_end: 15, display_name: "มัธยมศึกษาปีที่ 4–5 (Grades 9–11)", level_code: "UPPER_SECONDARY", annual_thb: 731000, notes: "Combined annual fees" },
      { grade_level: "Grade 12", order_start: 16, order_end: 16, display_name: "มัธยมศึกษาปีที่ 6 (Grade 12)", level_code: "UPPER_SECONDARY", annual_thb: 790500, notes: "Combined annual fees" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 5000, notes: "non-refundable" },
      { name: "Registration Fee", amount_thb: 200000, notes: "one-time, non-refundable" },
      { name: "Learning Resources Fee", amount_thb: 40000, notes: "one-time, non-refundable" },
      { name: "Re-enrollment Deposit", amount_thb: 50000, notes: "fully refundable deposit" },
      { name: "Campus Development Fee", amount_thb: 10000, notes: "annual, non-refundable" },
      { name: "Technology Fee", amount_thb: 6000, notes: "per semester" },
      { name: "Set Lunch, Snack & Milk", amount_thb: 16200, notes: "per semester" },
    ],
    tuition_min_thb: 538400,
    tuition_max_thb: 790500,
  },
  {
    school_name: "Harrow International School",
    homepage_url: "https://www.harrowschool.ac.th",
    status: "ok",
    page_scraped: "https://www.harrowschool.ac.th/admissions/tuition-fees",
    curriculum: "British",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Pre Nursery - Full day", order_start: 0, order_end: 0, display_name: "เตรียมอนุบาล (Pre-Nursery)", level_code: "PRE_NURSERY", annual_thb: 634600, notes: "Academic year 2026/27" },
      { grade_level: "Nursery - Full day", order_start: 1, order_end: 1, display_name: "เตรียมอนุบาล (Nursery)", level_code: "PRE_NURSERY", annual_thb: 737600, notes: "Academic year 2026/27" },
      { grade_level: "Reception", order_start: 4, order_end: 4, display_name: "อนุบาล 3 (Reception)", level_code: "KINDERGARTEN", annual_thb: 757600, notes: "Academic year 2026/27" },
      { grade_level: "Year 1 - Year 5", order_start: 5, order_end: 9, display_name: "ประถมศึกษาปีที่ 1–5 (Year 1–5)", level_code: "PRIMARY", annual_thb: 880300, notes: "Academic year 2026/27" },
      { grade_level: "Year 6 - Year 8", order_start: 10, order_end: 12, display_name: "ประถมศึกษาปีที่ 6 – มัธยมศึกษาปีที่ 2 (Year 6–8)", level_code: "LOWER_SECONDARY", annual_thb: 961900, notes: "Academic year 2026/27" },
      { grade_level: "Year 9 - Year 11", order_start: 13, order_end: 15, display_name: "มัธยมศึกษาปีที่ 3–5 (Year 9–11)", level_code: "UPPER_SECONDARY", annual_thb: 1040000, notes: "Academic year 2026/27" },
      { grade_level: "Year 12 - Year 13", order_start: 16, order_end: 16, display_name: "มัธยมศึกษาปีที่ 6 (Year 12–13)", level_code: "UPPER_SECONDARY", annual_thb: 1063000, notes: "Academic year 2026/27" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 5000, notes: "non-refundable" },
      { name: "Admission Fee", amount_thb: 225000, notes: "non-refundable, payable upon acceptance" },
      { name: "Deposit (Day student)", amount_thb: 200000, notes: "refundable upon departure" },
    ],
    tuition_min_thb: 634600,
    tuition_max_thb: 1063000,
  },
  {
    school_name: "ISB – International School Bangkok",
    homepage_url: "https://www.isb.ac.th",
    status: "ok",
    page_scraped: "https://www.isb.ac.th/admissions/fees",
    curriculum: "American",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Pre-Kindergarten", order_start: 0, order_end: 1, display_name: "เตรียมอนุบาล (Pre-Kindergarten)", level_code: "PRE_NURSERY", annual_thb: 659000, notes: "2026/27 School Year" },
      { grade_level: "Elementary (Grades KG-5)", order_start: 4, order_end: 9, display_name: "อนุบาล 3 – ประถมศึกษาปีที่ 5 (Elementary KG–5)", level_code: "PRIMARY", annual_thb: 1015000, notes: "2026/27 School Year" },
      { grade_level: "Middle (Grades 6-8)", order_start: 10, order_end: 12, display_name: "มัธยมศึกษาปีที่ 1–3 (Middle Grades 6–8)", level_code: "LOWER_SECONDARY", annual_thb: 1137000, notes: "2026/27 School Year" },
      { grade_level: "High (Grades 9-12)", order_start: 13, order_end: 16, display_name: "มัธยมศึกษาปีที่ 4–6 (High Grades 9–12)", level_code: "UPPER_SECONDARY", annual_thb: 1197000, notes: "2026/27 School Year" },
    ],
    hidden_costs: [
      { name: "Application Processing Fee", amount_thb: 4700, notes: "once only, non-refundable" },
      { name: "Registration Fee", amount_thb: 260000, notes: "one-time fee, payable first year" },
      { name: "Annual Fee", amount_thb: 22000, notes: "per year" },
      { name: "Transportation Fee (1 to 5 km)", amount_thb: 111300, notes: "whole year transport" },
      { name: "Transportation Fee (6 to 15 km)", amount_thb: 116600, notes: "whole year transport" },
      { name: "Transportation Fee (16 to 25 km)", amount_thb: 133300, notes: "whole year transport" },
    ],
    tuition_min_thb: 659000,
    tuition_max_thb: 1197000,
  },
  {
    school_name: "Shrewsbury International School",
    homepage_url: "https://www.shrewsbury.ac.th",
    status: "ok",
    page_scraped: "https://www.shrewsbury.ac.th/admissions/fees/overview/",
    curriculum: "British",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Early Years 1", order_start: 1, order_end: 1, display_name: "เตรียมอนุบาล (Early Years 1)", level_code: "PRE_NURSERY", annual_thb: 719400, notes: "Academic year 2026/27" },
      { grade_level: "Early Years 2", order_start: 2, order_end: 2, display_name: "อนุบาล 1 (Early Years 2)", level_code: "KINDERGARTEN", annual_thb: 757800, notes: "Academic year 2026/27" },
      { grade_level: "Years 1 – 2", order_start: 5, order_end: 6, display_name: "ประถมศึกษาปีที่ 1–2 (Years 1–2)", level_code: "PRIMARY", annual_thb: 851400, notes: "Academic year 2026/27" },
      { grade_level: "Years 3 – 4", order_start: 7, order_end: 8, display_name: "ประถมศึกษาปีที่ 3–4 (Years 3–4)", level_code: "PRIMARY", annual_thb: 913200, notes: "Academic year 2026/27" },
      { grade_level: "Years 5 – 6", order_start: 9, order_end: 10, display_name: "ประถมศึกษาปีที่ 5–6 (Years 5–6)", level_code: "PRIMARY", annual_thb: 944700, notes: "Academic year 2026/27" },
      { grade_level: "Years 7 – 9", order_start: 11, order_end: 13, display_name: "มัธยมศึกษาปีที่ 1–3 (Years 7–9)", level_code: "LOWER_SECONDARY", annual_thb: 976800, notes: "Academic year 2026/27" },
      { grade_level: "Year 10", order_start: 14, order_end: 14, display_name: "มัธยมศึกษาปีที่ 4 (Year 10)", level_code: "UPPER_SECONDARY", annual_thb: 1252200, notes: "Academic year 2026/27" },
      { grade_level: "Year 11", order_start: 15, order_end: 15, display_name: "มัธยมศึกษาปีที่ 5 (Year 11)", level_code: "UPPER_SECONDARY", annual_thb: 834800, notes: "Academic year 2026/27" },
      { grade_level: "Year 12", order_start: 16, order_end: 16, display_name: "มัธยมศึกษาปีที่ 6 (Year 12)", level_code: "UPPER_SECONDARY", annual_thb: 1256700, notes: "Academic year 2026/27" },
      { grade_level: "Year 13", order_start: 16, order_end: 16, display_name: "มัธยมศึกษาปีที่ 6 (Year 13)", level_code: "UPPER_SECONDARY", annual_thb: 837800, notes: "Academic year 2026/27" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 5000, notes: "per child, non-refundable" },
      { name: "Guaranteed Place Fee", amount_thb: 225000, notes: "non-refundable admission fee" },
      { name: "Refundable Deposit", amount_thb: 225000, notes: "refundable on departure" },
    ],
    tuition_min_thb: 719400,
    tuition_max_thb: 1256700,
  },
  {
    school_name: "NIST International School",
    homepage_url: "https://www.nist.ac.th",
    status: "ok",
    page_scraped: "https://www.nist.ac.th/admissions/tuition-fees",
    curriculum: "IB",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Early Childhood (Pre-K - KG)", order_start: 0, order_end: 4, display_name: "เตรียมอนุบาล – อนุบาล 3 (Early Childhood / PYP)", level_code: "KINDERGARTEN", annual_thb: 540000, notes: "Full IB Continuum" },
      { grade_level: "Primary (PYP Years 1-5)", order_start: 5, order_end: 9, display_name: "ประถมศึกษาปีที่ 1–5 (Primary PYP 1–5)", level_code: "PRIMARY", annual_thb: 680000, notes: "Full IB Continuum" },
      { grade_level: "Middle School (MYP Years 6-10)", order_start: 10, order_end: 14, display_name: "มัธยมศึกษาปีที่ 1–4 (Middle MYP 6–10)", level_code: "LOWER_SECONDARY", annual_thb: 780000, notes: "Full IB Continuum" },
      { grade_level: "High School (IB Diploma Years 11-12)", order_start: 15, order_end: 16, display_name: "มัธยมศึกษาปีที่ 5–6 (High School DP 11–12)", level_code: "UPPER_SECONDARY", annual_thb: 890000, notes: "Full IB Continuum" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 6000, notes: "non-refundable assessment" },
      { name: "Registration Fee", amount_thb: 260000, notes: "one-off enrollment fee" },
      { name: "Campus Development Deposit", amount_thb: 50000, notes: "refundable deposit" },
    ],
    tuition_min_thb: 540000,
    tuition_max_thb: 890000,
  },
];
