import type { ScrapedSchoolData } from "@/lib/calculatorUtils";

export const CALCULATOR_SEED_SCHOOLS: ScrapedSchoolData[] = [
  {
    school_name: "Bangkok Patana School",
    homepage_url: "https://www.patana.ac.th",
    status: "ok",
    page_scraped: "https://www.patana.ac.th/admissions/tuition-and-fees/",
    curriculum: "British",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Nursery", annual_thb: 515000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Foundation Stage 1", annual_thb: 577000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Foundation Stage 2", annual_thb: 640000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 1 - Year 2", annual_thb: 749000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 3", annual_thb: 790000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 4 - Year 5", annual_thb: 796000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 6", annual_thb: 811000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 7 - Year 9", annual_thb: 842000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 10", annual_thb: 957000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 11", annual_thb: 707000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 12", annual_thb: 1014000, semester_thb: null, notes: "Academic Year 2026/27" },
      { grade_level: "Year 13", annual_thb: 749000, semester_thb: null, notes: "Academic Year 2026/27" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 4000, notes: "once only" },
      { name: "Entrance Fee (First Child)", amount_thb: 250000, notes: "once only, non-refundable" },
      { name: "Entrance Fee (Second Child)", amount_thb: 200000, notes: "once only, non-refundable" },
      { name: "Deposit", amount_thb: 50000, notes: "refundable upon withdrawal" },
      { name: "Capital Assessment Fee", amount_thb: 30000, notes: "billed termly" },
      { name: "Extra-Curricular Activities Administrative Charge", amount_thb: 450, notes: "per student per ECA block" },
    ],
    tuition_min_thb: 515000,
    tuition_max_thb: 1014000,
  },
  {
    school_name: "Ruamrudee International School",
    homepage_url: "https://www.rism.ac.th",
    status: "ok",
    page_scraped: "https://www.rism.ac.th/admissions/tuition-fees/",
    curriculum: "American",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Pre-K & KG (2-4)", annual_thb: 538400, semester_thb: null, notes: "Combined annual fees" },
      { grade_level: "Grade 1", annual_thb: 544400, semester_thb: null, notes: "Combined annual fees" },
      { grade_level: "Grades 2-5", annual_thb: 718400, semester_thb: null, notes: "Combined annual fees" },
      { grade_level: "Grades 6-8", annual_thb: 686000, semester_thb: null, notes: "Combined annual fees" },
      { grade_level: "Grades 9-11", annual_thb: 731000, semester_thb: null, notes: "Combined annual fees" },
      { grade_level: "Grade 12", annual_thb: 790500, semester_thb: null, notes: "Combined annual fees" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 5000, notes: "non-refundable" },
      { name: "Registration Fee", amount_thb: 200000, notes: "one-time, non-refundable" },
      { name: "Learning Resources Fee", amount_thb: 40000, notes: "one-time, non-refundable" },
      { name: "Re-enrollment Deposit", amount_thb: 50000, notes: "fully refundable deposit" },
      { name: "Campus Development Fee", amount_thb: 10000, notes: "annual, non-refundable" },
      { name: "Technology Fee", amount_thb: 6000, notes: "per semester" },
      { name: "Set Lunch, Snack & Milk", amount_thb: 16200, notes: "per semester" },
    ],
    tuition_min_thb: 538400,
    tuition_max_thb: 790500,
  },
  {
    school_name: "Harrow International School",
    homepage_url: "https://www.harrowschool.ac.th",
    status: "ok",
    page_scraped: "https://www.harrowschool.ac.th/admissions/tuition-fees",
    curriculum: "British",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Pre Nursery - Full day", annual_thb: 634600, semester_thb: null, notes: "Academic year 2026/27" },
      { grade_level: "Nursery - Full day", annual_thb: 737600, semester_thb: null, notes: "Academic year 2026/27" },
      { grade_level: "Reception", annual_thb: 757600, semester_thb: null, notes: "Academic year 2026/27" },
      { grade_level: "Year 1 - Year 5", annual_thb: 880300, semester_thb: null, notes: "Academic year 2026/27" },
      { grade_level: "Year 6 - Year 8", annual_thb: 961900, semester_thb: null, notes: "Academic year 2026/27" },
      { grade_level: "Year 9 - Year 11", annual_thb: 1040000, semester_thb: null, notes: "Academic year 2026/27" },
      { grade_level: "Year 12 - Year 13", annual_thb: 1063000, semester_thb: null, notes: "Academic year 2026/27" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 5000, notes: "non-refundable" },
      { name: "Admission Fee", amount_thb: 225000, notes: "non-refundable, payable upon acceptance" },
      { name: "Deposit (Day student)", amount_thb: 200000, notes: "refundable upon departure" },
    ],
    tuition_min_thb: 634600,
    tuition_max_thb: 1063000,
  },
  {
    school_name: "ISB – International School Bangkok",
    homepage_url: "https://www.isb.ac.th",
    status: "ok",
    page_scraped: "https://www.isb.ac.th/admissions/fees",
    curriculum: "American",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Pre-Kindergarten", annual_thb: 659000, semester_thb: 329500, notes: "2026/27 School Year" },
      { grade_level: "Elementary (Grades KG-5)", annual_thb: 1015000, semester_thb: 507500, notes: "2026/27 School Year" },
      { grade_level: "Middle (Grades 6-8)", annual_thb: 1137000, semester_thb: 568500, notes: "2026/27 School Year" },
      { grade_level: "High (Grades 9-12)", annual_thb: 1197000, semester_thb: 598500, notes: "2026/27 School Year" },
    ],
    hidden_costs: [
      { name: "Application Processing Fee", amount_thb: 4700, notes: "once only, non-refundable" },
      { name: "Registration Fee", amount_thb: 260000, notes: "one-time fee, payable first year" },
      { name: "Annual Fee", amount_thb: 22000, notes: "per year" },
      { name: "Transportation Fee (1 to 5 km)", amount_thb: 111300, notes: "whole year transport" },
      { name: "Transportation Fee (6 to 15 km)", amount_thb: 116600, notes: "whole year transport" },
      { name: "Transportation Fee (16 to 25 km)", amount_thb: 133300, notes: "whole year transport" },
    ],
    tuition_min_thb: 659000,
    tuition_max_thb: 1197000,
  },
  {
    school_name: "Shrewsbury International School",
    homepage_url: "https://www.shrewsbury.ac.th",
    status: "ok",
    page_scraped: "https://www.shrewsbury.ac.th/admissions/fees/overview/",
    curriculum: "British",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Early Years 1", annual_thb: 719400, semester_thb: 239800, notes: "Academic year 2026/27" },
      { grade_level: "Early Years 2", annual_thb: 757800, semester_thb: 252600, notes: "Academic year 2026/27" },
      { grade_level: "Years 1 – 2", annual_thb: 851400, semester_thb: 283800, notes: "Academic year 2026/27" },
      { grade_level: "Years 3 – 4", annual_thb: 913200, semester_thb: 304400, notes: "Academic year 2026/27" },
      { grade_level: "Years 5 – 6", annual_thb: 944700, semester_thb: 314900, notes: "Academic year 2026/27" },
      { grade_level: "Years 7 – 9", annual_thb: 976800, semester_thb: 325600, notes: "Academic year 2026/27" },
      { grade_level: "Year 10", annual_thb: 1252200, semester_thb: 417400, notes: "Academic year 2026/27" },
      { grade_level: "Year 11", annual_thb: 834800, semester_thb: 417400, notes: "Academic year 2026/27" },
      { grade_level: "Year 12", annual_thb: 1256700, semester_thb: 418900, notes: "Academic year 2026/27" },
      { grade_level: "Year 13", annual_thb: 837800, semester_thb: 418900, notes: "Academic year 2026/27" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 5000, notes: "per child, non-refundable" },
      { name: "Guaranteed Place Fee", amount_thb: 225000, notes: "non-refundable admission fee" },
      { name: "Refundable Deposit", amount_thb: 225000, notes: "refundable on departure" },
    ],
    tuition_min_thb: 719400,
    tuition_max_thb: 1256700,
  },
  {
    school_name: "NIST International School",
    homepage_url: "https://www.nist.ac.th",
    status: "ok",
    page_scraped: "https://www.nist.ac.th/admissions/tuition-fees",
    curriculum: "IB",
    tuition_found: true,
    tuition_by_grade: [
      { grade_level: "Early Childhood (Pre-K - KG)", annual_thb: 540000, semester_thb: 270000, notes: "Full IB Continuum" },
      { grade_level: "Primary (PYP Years 1-5)", annual_thb: 680000, semester_thb: 340000, notes: "Full IB Continuum" },
      { grade_level: "Middle School (MYP Years 6-10)", annual_thb: 780000, semester_thb: 390000, notes: "Full IB Continuum" },
      { grade_level: "High School (IB Diploma Years 11-12)", annual_thb: 890000, semester_thb: 445000, notes: "Full IB Continuum" },
    ],
    hidden_costs: [
      { name: "Application Fee", amount_thb: 6000, notes: "non-refundable assessment" },
      { name: "Registration Fee", amount_thb: 260000, notes: "one-off enrollment fee" },
      { name: "Campus Development Deposit", amount_thb: 50000, notes: "refundable deposit" },
    ],
    tuition_min_thb: 540000,
    tuition_max_thb: 890000,
  },
];
