/**
 * api/schoolsApi.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Backend service layer for School data.
 *
 * Currently reads from the mock database (src/db/) and merges with scraped
 * results from results.json (produced by testz.py) if available.
 */

import type { School, SchoolDetail } from "@/types";
import { SCHOOLS_SEED } from "@/api/mock/schools";
import { SCHOOL_DETAILS_SEED } from "@/api/mock/schoolDetails";

let cachedSchools: School[] | null = null;
let cachedDetails: Record<number, SchoolDetail> | null = null;

/**
 * Loads seed data and overrides it dynamically with live scraped results
 * from `results.json` (if the file has been generated by the python scraper).
 */
async function getMergedData() {
  if (cachedSchools && cachedDetails) {
    return { schools: cachedSchools, details: cachedDetails };
  }

  // Clone seed data to avoid direct mutation issues
  const schools = SCHOOLS_SEED.map((s) => ({ ...s }));
  const details = Object.keys(SCHOOL_DETAILS_SEED).reduce((acc, key) => {
    const id = Number(key);
    acc[id] = {
      ...SCHOOL_DETAILS_SEED[id],
      fees: SCHOOL_DETAILS_SEED[id].fees.map((f) => ({ ...f })),
      accreditation: [...SCHOOL_DETAILS_SEED[id].accreditation],
      gallery: [...SCHOOL_DETAILS_SEED[id].gallery],
      facilities: [...SCHOOL_DETAILS_SEED[id].facilities],
      reviews: SCHOOL_DETAILS_SEED[id].reviews.map((r) => ({ ...r })),
    };
    return acc;
  }, {} as Record<number, SchoolDetail>);

  try {
    const res = await fetch("/results.json");
    if (res.ok) {
      const scraped = await res.json();
      if (Array.isArray(scraped)) {
        scraped.forEach((item) => {
          if (!item || item.status !== "ok") return;

          // Match school by name (case-insensitive substring check)
          const matchedSchool = schools.find(
            (s) =>
              s.name.toLowerCase().includes(item.school_name.toLowerCase()) ||
              item.school_name.toLowerCase().includes(s.name.toLowerCase())
          );

          if (matchedSchool) {
            // Update curriculum
            if (item.curriculum && item.curriculum.toLowerCase() !== "unclear") {
              matchedSchool.curriculum = item.curriculum;
            }

            // Update starting tuition
            if (item.tuition_min_thb !== null && item.tuition_min_thb !== undefined) {
              matchedSchool.tuitionStart = item.tuition_min_thb;
            }

            // Update detailed info (fees table)
            const detailRecord = details[matchedSchool.id];
            if (detailRecord) {
              const newFees: { label: string; amount: string }[] = [];

              // Scraped tuition fee lines
              if (Array.isArray(item.tuition_by_grade)) {
                item.tuition_by_grade.forEach((g: any) => {
                  if (g && g.grade_level) {
                    const amountText = g.annual_thb
                      ? `฿${g.annual_thb.toLocaleString()} / yr`
                      : g.semester_thb
                      ? `฿${(g.semester_thb * 2).toLocaleString()} / yr`
                      : "Contact school";
                    newFees.push({
                      label: `Tuition (${g.grade_level})`,
                      amount: amountText,
                    });
                  }
                });
              }

              // Scraped hidden fee lines
              if (Array.isArray(item.hidden_costs)) {
                item.hidden_costs.forEach((c: any) => {
                  if (c && c.name) {
                    const note = c.notes ? ` (${c.notes})` : "";
                    const amountText = c.amount_thb
                      ? `฿${c.amount_thb.toLocaleString()}`
                      : "Contact school";
                    newFees.push({
                      label: `${c.name}${note}`,
                      amount: amountText,
                    });
                  }
                });
              }

              if (newFees.length > 0) {
                detailRecord.fees = newFees;
              }
            }
          }
        });
      }
    }
  } catch (error) {
    console.debug("scraper results.json not loaded:", error);
  }

  cachedSchools = schools;
  cachedDetails = details;
  return { schools, details };
}

// ─── Schools ──────────────────────────────────────────────────────────────────

/**
 * Fetch all schools.
 */
export async function getSchools(): Promise<School[]> {
  const data = await getMergedData();
  return data.schools;
}

/**
 * Fetch a single school by ID.
 */
export async function getSchoolById(id: number): Promise<School | undefined> {
  const data = await getMergedData();
  return data.schools.find((s) => s.id === id);
}

/**
 * Fetch the extended detail record for a school.
 */
export async function getSchoolDetail(id: number): Promise<SchoolDetail | undefined> {
  const data = await getMergedData();
  return data.details[id] ?? data.details[1];
}

